#!/bin/sh

cd "$HOME"

shopt -s dotglob

for item in *; do

	base_item=$(basename "$item")

	echo "working on $base_item"

	if [[ "$base_item" == "desktop" || "$base_item" == "Downloads" || "$base_item" == "setup.artix" || "$base_item" == ".ssh" ]]; then
		echo "skipping $base_item"
		continue
	fi

	echo "deleting $base_item"

	sudo rm -rf -- "$item"
done

shopt -u dotglob

echo "Deletion complete"
