#!/bin/sh

# Install dwm dependencies
sudo pacman -S --noconfirm xorg-server xorg-xinit xorg-xsetroot

# Create the .local/src directory if it doesn't exist
mkdir -p ~/.local/src

# Clone dwm if it's not already present
git clone https://github.com/m-c-frank/dwm.git ~/.local/src/dwm

# Compile and install dwm
cd ~/.local/src/dwm
sudo make clean install

# Copy the provided .xinitrc to the home directory
cp ./configs/xinitrc ~/.xinitrc
