#!/bin/sh

# Install dwm dependencies
sudo pacman -S --noconfirm xorg-server xorg-xinit xorg-xsetroot xwallpaper

# Create the .local/src directory if it doesn't exist
mkdir -p "$HOME/.local/src"

# Clone dwm if it's not already present
git clone https://github.com/m-c-frank/dwm.git "$HOME/.local/src/dwm"

# Compile and install dwm
cd "$HOME/.local/src/dwm"
sudo make clean install

# Copy the provided .xinitrc to the home directory
cp "$HOME/setup.artix/configs/xinitrc" "$HOME/.xinitrc"
